version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
        - gofibernetwork

  fiber-boilerplate:
    build: .
    container_name: fiber-boilerplate
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql
    ports:
      - "3300:3300"
    # command: "./fiber-boilerplate"
    volumes:
      - .:/fiber-boilerplate
    networks:
      - gofibernetwork

networks:
  gofibernetwork:
